# Generated by Django 3.2.12 on 2022-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=100)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('needing_repair', models.BooleanField(blank=True, null=True)),
                ('durability', models.FloatField(blank=True, null=True)),
                ('max_durability', models.FloatField(blank=True, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('minimum_rent_period', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
